Traceback (most recent call last):
  File "/usr/local/Caskroom/mambaforge/base/envs/climate-guide/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/Caskroom/mambaforge/base/envs/climate-guide/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/Caskroom/mambaforge/base/envs/climate-guide/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/Caskroom/mambaforge/base/envs/climate-guide/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/Caskroom/mambaforge/base/envs/climate-guide/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/local/Caskroom/mambaforge/base/envs/climate-guide/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/usr/local/Caskroom/mambaforge/base/envs/climate-guide/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/Caskroom/mambaforge/base/envs/climate-guide/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
result = ctx.search()[0]
result.dataset_id
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mIndexError[0m                                Traceback (most recent call last)
Input [0;32mIn [3][0m, in [0;36m<cell line: 1>[0;34m()[0m
[0;32m----> 1[0m result [38;5;241m=[39m [43mctx[49m[38;5;241;43m.[39;49m[43msearch[49m[43m([49m[43m)[49m[43m[[49m[38;5;241;43m0[39;49m[43m][49m
[1;32m      2[0m result[38;5;241m.[39mdataset_id

File [0;32m/usr/local/Caskroom/mambaforge/base/envs/climate-guide/lib/python3.10/site-packages/pyesgf/search/results.py:53[0m, in [0;36mResultSet.__getitem__[0;34m(self, index)[0m
[1;32m     50[0m ResultClass [38;5;241m=[39m _result_classes[search_type]
[1;32m     52[0m [38;5;66;03m# !TODO: should probably wrap the json inside self.__batch_cache[39;00m
[0;32m---> 53[0m [38;5;28;01mreturn[39;00m ResultClass([43mbatch[49m[43m[[49m[43moffset[49m[43m][49m, [38;5;28mself[39m[38;5;241m.[39mcontext)

[0;31mIndexError[0m: list index out of range
IndexError: list index out of range

